import "bootstrap";
import { search } from '../components/search';
import { translate } from '../components/translate';
import { openForm } from '../components/openForm';
import { hideImage } from '../components/hideImage';
import { typedText } from '../components/typedText';
typedText();
search();
translate();
openForm();
hideImage();
